excerpt_separator: ""
highlighter: rouge
markdown: kramdown
url: http://brlmski.github.io
title: eternalstats
tagline: information and tools (soonâ„¢) for Eternal Card Game by brlmski
description: The ruminations of one Eternal player trying to look at the bigger picture
paginate: 5
